### ISSUE TITLE
Review Windows-specific code

### ISSUE THREAD

**Issue by soc** [soc/directories-rs#1]
I'm not a Windows developer, so I'm not experienced in dealing with the various native Windows APIs.

It would be really helpful if someone more knowledgeable than me could have a look at https://github.com/soc/directories-rs/blob/master/src/win.rs#L82 and make sure that I have used the Windows API correctly, and haven't introduced any glaring issues on the Rust side either.

**Comment by soc** [comment]
@francesca64 Amazing, thanks a lot!

Could you have a look whether https://github.com/soc/directories-rs/blob/master/src/win.rs#L84 correctly manages the memory coming from the Windows API?

**Comment by francesca64** [comment]
Looks good to me. `OsString` copies the data, and you free the original with `CoTaskMemFree` just as the docs for `SHGetKnownFolderPath ` say.

**Comment by soc** [comment]
@francesca64 Thank you. I looked at code like https://github.com/tbu-/dirs/blob/master/src/windows/sys.rs#L88 that explicitly defined `Drop`and was concerned that there was a way to leave the method in my code without cleanup that I didn't see..

**Comment by soc** [comment]
@francesca64 Last question: Do the changes in https://github.com/soc/directories-rs/commit/ae98d152641c7b68904e1f0ee1d86354761fd0c9 look good to you?

**Comment by soc** [comment]
@francesca64 Thanks for your help! I'll close this ticket then.
