### ISSUE TITLE
Calling `xdg-user-dirs` on linux takes non-negligible amount of time

### ISSUE THREAD

**Issue by matklad** [soc/directories-rs#16]
If I have `xdg-user-dirs` utility installed, then creating `BaseDirs` on my machine takes about 18 milliseconds, which seems pretty substantiation. If I don't have `xdg-user-dirs`, the time is 2 ms. Finally, if I patch `directories-rs` to just return `None` from `run_xdg_user_dir_command`, the time drops to 8 μs. 

Given that `xdg-user-dirs` is used for stuff like `audio_dir`, which is probably isn't required for some of potential clients of directories-rs, like Cargo and rustup, I wonder if we should try to optimize away this overhead? Some possible solutions:

1) Remove `audio_dir` and such from API altogether for now.
2) On Linux, use `lazy_cell` to call `xdg-user-dirs` only when necessary.
3) Move `audio_dir` and friends to another struct.
4) Reimplement `xdg-user-dirs` as a Rust library: looks like xdg-user-dirs basically just reads `~/.config/user-dirs.dirs` file, so re implementing it should not be super complicated, and should bring substantial performance improvements by removing process spawning overhead.

**Comment by soc** [comment]
Thanks for benchmarking!

One thing that effected this the design was the desire to have `BaseDirs::new` and `ProjectDirs::from` be immutable snapshots that reflect the state of the various variables at the time the struct was created
Without this restraint I would have gone for laziness.

What I would propose is two-fold:

- Replacing the invocation of the command-line tool with reading the config file directly. Maybe we can get to an acceptable level of performance with this.
- If this is not enough, I'll think about splitting the `xdg-user`dirs` part off from `BaseDirs`, into it's own struct. Then we would have `BaseDirs`, `UserDirs` and `ProjectDirs`.

What do you think?

**Comment by matklad** [comment]
Agree that laziness is a wrong solution here.

Long term, I think reading he config ourselves seems to be a way to go: at least on my machine, I have the config file, but I don’t have the actual utility installed.

However, even if reading file is fast, I would still feel a bit uneasy about this bit of IO, because IO tends to fail for obscure reasons...And it seems plausible that UserDirs will be used less often than BaseDirs. So perhaps moving them to a separate struct makes sense regardless of performance per se?

**Comment by matklad** [comment]
https://github.com/whitequark/rust-xdg/issues/1 Seems relevant

**Comment by soc** [comment]
THANKS! Your link was extremely useful!

Some of the failures I saw on Travis not having `xdg-user-dirs` hinted into this being a problem, but the discussion and the Debian bug brought additional clarity.


Also, it reminded me about the Trash dir, which I completely forgot and for which I should definitely add support!

Given all this information, let's do this:

- `BaseDirs`: cache, config, data, etc. (~ dot directories)
- `UserDirs`: audio, video, trash, etc. (user-visible dirs)
- `ProjectDirs`: as-is

The only question I have is whether the home dir should be in UserDirs, BaseDirs, or both ... opinions? I'd probably go for UserDirs, as it is a user-visible dir, but then we would have the same issue with UserDirs computing all the extra stuff just to provide the home dir ...

What do you think?

**Comment by matklad** [comment]
home dir will definitely be among the most used directories, so, from the practical standpoint, it should go into `BaseDirs`.

**Comment by soc** [comment]
@matklad: https://github.com/soc/directories-rs/pull/17

**Comment by soc** [comment]
I think we should at least batch the queries, so we spawn only one process instead of a dozen like in https://github.com/soc/directories-jvm/blob/master/src/main/java/io/github/soc/directories/Util.java#L95.

**Comment by soc** [comment]
Ooops, sorry.

**Comment by soc** [comment]
This issue has been resolved in 2.0.0.

Thanks for reporting this, @matklad!
