### ISSUE TITLE
Consider the Rust API Guidelines 

### ISSUE THREAD

**Issue by dwijnand** [soc/directories-rs#20]
https://rust-lang-nursery.github.io/api-guidelines/

just sharing what I came across. perhaps you're already aware of them.

**Comment by soc** [comment]
Thanks, I'll have a look!

Perfect timing by the way, was just giving a talk about this library. :-)

**Comment by dwijnand** [comment]
nope, just thought you'd be interested.

I've yet to find the time to sit down and read through it all myself.

**Comment by dwijnand** [comment]
feel free to close this issue as and when you please - I don't have any specific outcome attached to it.

**Comment by soc** [comment]
Ah, ok thanks! I went through it, but I couldn't find a recommendation that the code was violating.

> feel free to close this issue as and when you please - I don't have any specific outcome attached to it.

Then I'll close this for the moment, but please reopen this at any time you feel there is something that can be improved.

Thanks!
