### ISSUE TITLE
CI: Pin a minimum supported stable Rust version

### ISSUE THREAD

**Issue by b-r-u** [soc/directories-rs#32]
To avoid accidentally increasing the minimum supported Rust version, the CI scripts could include a build for a fixed stable Rust version.
I'm not sure what the minimum working version is right now (I tried to lower it with https://github.com/soc/directories-rs/pull/31), because I couldn't test all platforms.

**Comment by b-r-u** [comment]
Ok, so I tested different Rust versions on a fork (https://github.com/b-r-u/directories-rs/commits/ci-rust-1.20) and it looks like everything works even with 1.13 (from 2016-11-10, which stabilized the `?` operator) with a minor change (https://github.com/b-r-u/directories-rs/commit/746679109bfad5eefed8c4bf2057295e78260a50).

I also conducted a small survey on the minimum version of some popular crates:

Crate | Minimum Version
----- | ---------------
serde | 1.13
log | 1.16
lazy_static | 1.21
regex | 1.20

https://github.com/rust-lang/regex#minimum-rust-version-policy

**Comment by soc** [comment]
Thanks @b-r-u, I'll look into this tomorrow!

**Comment by b-r-u** [comment]
> so what I'm wondering is whether there is some way to explicitly set minimal versions for Rust and crates in a separate CI run.

There is https://github.com/rust-lang/cargo/issues/4100 for minimal crate versions but I think it's not yet stable.

> Apart from that, would you suggest lowering the crate versions mentioned in cargo.toml to the minimum you figured out here?

Maybe there was a misunderstanding? I was looking at popular crates to get a feeling for the minimal Rust version they support. I don't think you should lower any dependency versions.

**Comment by soc** [comment]
Ah, alright, understood. Thanks!

**Comment by b-r-u** [comment]
I could have been clearer and updated the comment! https://github.com/soc/directories-rs/issues/32#issuecomment-394413593
