### ISSUE TITLE
Should home_dir on Windows consider %USERPROFILE%?

### ISSUE THREAD

**Issue by soc** [soc/directories-rs#33]
Making `home_dir` consider `%USERPROFILE%` on Windows would be more in line with its behavior on Linux, but I'm not really sure what the best practices around changing `%USERPROFILE%` on Windows are.

I assume that this happens far less frequently on Windows than it does on Linux, and I'd appreciate comments and experience reports from people who have done this to better understand their use cases.

**Comment by mqudsi** [comment]
Generally, no application or user files are ever placed directly in `C:\Users\USERNAME`, although cross-platform linux apps have made it a habit of creating `.appname` folders to store their config there akin to under `$HOME`.

**Comment by soc** [comment]
I'm closing this due to a lack of new information about this issue since it was opened.

Everyone should feel free to reopen this issue with new pieces of information or specific use-cases.
