### ISSUE TITLE
Relicense under MIT/Apache-2

### ISSUE THREAD

**Issue by soc** [soc/directories-rs#36]
It has been brought up repeatedly that MIT/Apache-2 is the preferred license, especially for crates the core ecosystem might depend on (like cargo).

Steps that would be necessary:
- Ask contributors whether this is fine for them
  - [x] @b-r-u 
  - [x] @Calinou 
  - [x] @tbu- 
  - [x] @matklad 
  - [x] @spacekookie 
- If all agree, change license.
- Publish new version, probably combined with the necessary fixes/changes around `home_dir`.

**Comment by b-r-u** [comment]
I'm also fine with MIT/Apache-2.

**Comment by soc** [comment]
@b-r-u You beat me to it! Thanks!

@Calinou, @tbu-, @matklad, @spacekookie could you also comment whether you are fine with this?

**Comment by spacekookie** [comment]
Yea, I'm fine with this change :+1:

**Comment by soc** [comment]
@spacekookie Thanks! (Hope you enjoyed the GPN, btw! :-D)

**Comment by spacekookie** [comment]
@soc Yea it was really fun :wink: :wink:

**Comment by tbu-** [comment]
I appreciate this change (and obviously also agree with it). :)

**Comment by matklad** [comment]
I agree to change the license to MIT/Apache-2.

**Comment by Calinou** [comment]
I agree with this change :smiley:

**Comment by soc** [comment]
Thanks to everyone, it looks like we have all the OK's we need!

Here is my plan for the near future:

I'll relicense the library in the coming days, work on https://github.com/soc/directories-rs/issues/37 (comments appreciated) and then push 1.0!

**Comment by soc** [comment]
Hey everyone, would you mind giving me a last round of review for https://github.com/soc/directories-rs/pull/38 before I release 1.0? Would really appreciate it!
