### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by killercup** [soc/directories-rs#4]
- Add Travis CI for Linux and macOS
- Add AppVeyor for Windows

**Comment by soc** [comment]
Thanks, I have activated both TravisCI and AppVeyor!

Are there any travis.yml and appveyor.yml example files for Rust anywhere that I can adapt?

**Comment by killercup** [comment]
Have a look at https://crate-ci.github.io/pr/testing.html

cc @epage

**Comment by soc** [comment]
Thanks!

**Comment by soc** [comment]
I set things up and added the badges to the README. Thanks!
