### ISSUE TITLE
Documentation for `BaseDirs` mentions panicing, but the function returns None

### ISSUE THREAD

**Issue by krdln** [soc/directories-rs#44]
Documentation for `BaseDirs::new` contains the following:

>  # Panics
>
> Panics if the home directory cannot be determined. See [`home_dir`].

but from my understanding, the function returns `None` in the circumstance. Also, `home_dir` links to `std::env::home_dir`, but the implementation in this crate is different wrt. handling of empty paths. Should it link to `dirs::home_dir` instead?

**Comment by soc** [comment]
You are right on both cases, there is something wrong here:

- I think this bit of documentation is still from the time where `new` returned `BaseDir` instead of `Option<BaseDir>`.
- The link certainly should go to `dirs::home_dir`.

**Comment by soc** [comment]
@krdln I pushed commit https://github.com/soc/directories-rs/commit/0a424937234a9002e04c14d7da6e898766672f72, could you have a look whether this addresses the issues from your point of view? Thanks!

**Comment by krdln** [comment]
@soc Thanks for quick fix!

I still feel it's a little bit confusing:

> ```rust
> /// The returned value depends on the operating system and is either `Some`, containing a value from the following table, or `None`.
> /// ...
> pub fn home_dir(&self) -> &Path { ... }
> ```

These docs about some/none are attached to a `home_dir` function, which doesn't return `Option`. Perhaps you've meant to put them on the `BaseDirs::new` docs?

Also, forgot to mention in the original issue, similar notes about panic are also on `ProjectDirs::new` and `UserDirs::new`.

**Comment by soc** [comment]
Ouch, yes you are right. I just copied the documentation from `dirs` without checking.

**Comment by soc** [comment]
@krdln Could you have a look at https://github.com/soc/directories-rs/commit/4026a64c3eb48d9af6186e5c700ed26a8aa5864d? Anything missing?

**Comment by krdln** [comment]
It's perfectly clear now. Thank you!
