### ISSUE TITLE
ProjectDirs path problem under Windows

### ISSUE THREAD

**Issue by mqudsi** [soc/directories-rs#45]
Under Windows, there is a split between the local appdata folder and the roaming appdata folder. With regards to what goes where, they're almost interchangeable except that the roaming folder is for user app data that should be synchronized across machines while the local folder is for user app data that is machine-specific and need not/should not be synchronized to other machines. 

(The only time any of this comes into play is when people are connected to a domain and using roaming profiles which brings their environment with them each time they log onto a machine, even if it's not "their" machine.)

I'm not sure the decision to use the roaming folder for `ProjectDirs` is correct given that the description says it's for caching, etc. and caches should generally not be synchronized.

e.g. Chrome stores its caches and more under `%localappdata%` and not `%appdata%`, Microsoft stores a user's own crash dumps under `%localappdata%` while they store things like the dictionaries that a user has installed to `%appdata%`.

But configuration (aka `$HOME/.config`) definitely belongs in `%roamingappdata%`.

**Comment by soc** [comment]
I'm closing this issue, feel free to re-open it with additional information.
