### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by killercup** [soc/directories-rs#5]
Ideally, compile with `#![deny(missing_docs)]`

**Comment by soc** [comment]
Ok, thanks, will look into this!

**Comment by soc** [comment]
Added a first, rough part of documentation in https://github.com/soc/directories-rs/commit/d744387ed3b0d4f05bc8440aab7272848d87db97?diff=unified

**Comment by soc** [comment]
Status: some documentation has been added, but more is required.

**Comment by soc** [comment]
Everything public should be implemented now in https://github.com/soc/directories-rs/pull/15.

Please reopen if something is missing!
