### ISSUE TITLE
Documentation for `ProjectDirs::from` mentions panicing, but the function returns None

### ISSUE THREAD

**Issue by ypoluektovich** [soc/directories-rs#59]
The same issue as #44, apparently.

(I haven't checked, but maybe there are even more of these? ;-)

**Comment by soc** [comment]
Hi Yanus,

thanks for your report! Could you have a look whether the change looks good to you?
(If not, please reopen with feedback!)

Cheers,

Simon

**Comment by ypoluektovich** [comment]
Yep, that looks good! Thanks for the super quick response :)

**Comment by soc** [comment]
:-)
