### ISSUE TITLE
Access directories with getters

### ISSUE THREAD

**Issue by killercup** [soc/directories-rs#7]
Currently, the fields of `BaseDirectories` and `ProjectDirectories` are private, and can't be accessed by external crates. I propose we add getters that return `Path`/`Option<Path>`.

**Comment by soc** [comment]
Thanks, that's an embarrassing oversight.
What would be the difference to just making the struct fields public?

**Comment by killercup** [comment]
> What would be the difference to just making the struct fields public?

Changing public fields is a breaking change (even adding them if all are public, because external users can construct the struct).

**Comment by soc** [comment]
Alright, thanks!

Why `Path` instead of `PathBuf`? To simplify the ownership situation?

**Comment by killercup** [comment]
Yeah.

IIRC Path is to PathBuf as &str is to String.

**Comment by soc** [comment]
Ok, thanks! Expect fixes to arrive today.

**Comment by soc** [comment]
@killercup Can you have a look at https://github.com/soc/directories-rs/pull/8?

**Comment by soc** [comment]
Fixed in https://github.com/soc/directories-rs/pull/8!
