### ISSUE TITLE
Consider using config and data subdirectories for {FOLDERID_RoamingAppData} on Windows

### ISSUE THREAD

**Issue by soc** [soc/directories-rs#9]
**Status Quo**

    BaseDirs::config_dir:   {FOLDERID_RoamingAppData}
    BaseDirs::data_dir:     {FOLDERID_RoamingAppData}
    ProjectDirs.config_dir: {FOLDERID_RoamingAppData}/_yourprojectname_/
    ProjectDirs.data_dir:   {FOLDERID_RoamingAppData}/_yourprojectname_/

**Alternative A:** Add config/data sub-directories to the paths of both `BaseDirs::{config,data}_dir` and  `ProjectDirs.{config,data}_dir`

    BaseDirs::config_dir:   {FOLDERID_RoamingAppData}/config/
    BaseDirs::data_dir:     {FOLDERID_RoamingAppData}/data/
    ProjectDirs.config_dir: {FOLDERID_RoamingAppData}/_yourprojectname_/config/
    ProjectDirs.data_dir:   {FOLDERID_RoamingAppData}/_yourprojectname_/data/

Benefits:

- More overall consistency across Linux, macOS and Windows
- config and data is cleanly separated, not put into the same folder

Drawbacks:

- Not an established standard on Windows. The structure might be fine for the project directories, but less so for the general base directories.

**Alternative B:** Add config/data sub-directories only to the paths of  `ProjectDirs.{config,data}_dir`

    BaseDirs::config_dir:   {FOLDERID_RoamingAppData}/
    BaseDirs::data_dir:     {FOLDERID_RoamingAppData}/
    ProjectDirs.config_dir: {FOLDERID_RoamingAppData}/_yourprojectname_/config/
    ProjectDirs.data_dir:   {FOLDERID_RoamingAppData}/_yourprojectname_/data/

Benefits:

- Slightly more overall consistency across Linux, macOS and Windows
- config and data of applications is cleanly separated, not put into the same folder

Drawbacks:

- Slightly less internal consistency of `BaseDirs` and `ProjectDirs` on Windows.

**Additional Consideration**

    BaseDirs::cache_dir:   {FOLDERID_AppData}/cache

Note the `cache` directory that is appended to the path. It might make sense to consider whether it makes sense to change this, depending on the alternative that is picked.

**Comment by soc** [comment]
Do you have an opinion on this, @killercup?

**Comment by killercup** [comment]
Sorry, I have no experience developing for Windows (or using it, really).

**Comment by soc** [comment]
No, problem, thanks!

**Comment by lnicola** [comment]
> The structure might be fine for the project directories, but less so for the general base directories.

I tend to agree. It would be a bit strange on Windows.

Even more, there would be no direct way of querying `{FOLDERID_RoamingAppData}`. I imagine apps might ask for `config_dir` or `data_dir` for two reasons:

- they don't like what `directories` picks for the project directories, and want to build the path themselves
- they want to read the files of another application

Being opinionated about splitting `config` and `data` would help in neither of these cases.

**Comment by soc** [comment]
@lnicola Thanks for your input!

It would certainly be possible to keep `BaseDirs` as is (`{FOLDERID_RoamingAppData}`) and only adjust the directories for `ProjectDirs`.

What's your take on this?

My main concern with having no sub-directories for `ProjectDirs` is that users might write code like "get the config dir and copy/move all the files to place X" (e. g. app backups, migration, ...) and their code would look perfectly fine, but the code would unintentionally also end up copying/moving data files.

I think this would be extremely unintuitive and could cause unexpected bugs.

**Comment by lnicola** [comment]
`ProjectDirs` is harder, and I have no strong opinion either way. One could argue that the table in the README clearly shows the two paths to be the same, but it's a small thing that people might end forgetting after a while. On the other hand, one day someone is sure to show up and complain there's an annoying `config` subdirectory that they don't want to see.

So.. I don't know :confused: .

**Comment by soc** [comment]
@lnicola Ok, thanks! I'm slightly inclined toward going with Alternative B over status-quo and Alternative A.

**Comment by ollie27** [comment]
I recommend not using subdirectories in `BaseDirs`. I notice `cache_dir` is `{FOLDERID_LocalAppData}\cache\` which doesn't make much sense. That should just be `{FOLDERID_LocalAppData}`.

For `ProjectDirs` using subdirectories seems fine as long as it's done consistently on all platforms.

**Comment by soc** [comment]
@ollie27 The cache subdirectory comes from Qt's StandardPaths. I agree that it might make sense to go either all-or-nothing with config/cache/data.

**Comment by ollie27** [comment]
I don't think following Qt's StandardPaths is a good idea there.

`data_dir` and `data_local_dir` overlap on Linux and macOS so exactly the same problem exists there, why not use subdirectories for them? Maybe the easiest solution is to make it clear in the docs that directories can and do overlap.

**Comment by soc** [comment]
That's a very good point, thanks!

**Comment by soc** [comment]
Hi every, could you have a look at the PR?

**Comment by soc** [comment]
Alternative B, with \cache\ removed from `BaseDirs.cache_dir`, implemented in https://github.com/soc/directories-rs/pull/15.

Thanks to everyone involved!
